import { API_COURSES_PATHS } from "./api.routes";

////////////////////////////////// USER ENDPOINTS
const ALLCOURSESFREE = `${API_COURSES_PATHS.ALLCOURSESFREE}`;
const GETCOURSEBYID = `${API_COURSES_PATHS.GETCOURSEBYID}`;
const GETCOURSEBYIDFREE = `${API_COURSES_PATHS.GETCOURSEBYIDFREE}`;

export { ALLCOURSESFREE, GETCOURSEBYID, GETCOURSEBYIDFREE };
