import { API_ANALYTICS_PATHS } from "./api.routes";

////////////////////////////////// NOTIFICATION ENDPOINTS
const GETORDERSANALYTICS = `${API_ANALYTICS_PATHS.GETORDERSANALYTICS}`;
const GETUSERSANALYTICS = `${API_ANALYTICS_PATHS.GETUSERSANALYTICS}`;
const GETCOURSESANALYTICS = `${API_ANALYTICS_PATHS.GETCOURSESANALYTICS}`;

export { GETORDERSANALYTICS, GETUSERSANALYTICS, GETCOURSESANALYTICS };
