import { API_COURSES_PATHS } from "./api.routes";

////////////////////////////////// COURSE ENDPOINTS
const ALLCOURSESFREE = `${API_COURSES_PATHS.ALLCOURSESFREE}`;
const GETCOURSEBYID = `${API_COURSES_PATHS.GETCOURSEBYID}`;
const GETCOURSEBYIDFREE = `${API_COURSES_PATHS.GETCOURSEBYIDFREE}`;
const GETCOURSECONTENTBYID = `${API_COURSES_PATHS.GETCOURSECONTENTBYID}`;
const ADDQUESTION = `${API_COURSES_PATHS.ADDQUESTION}`;
const ADDREPLYTOQUESTION = `${API_COURSES_PATHS.ADDREPLYTOQUESTION}`;
const ADDCOURSEREVIEWBYID = `${API_COURSES_PATHS.ADDCOURSEREVIEWBYID}`;
const ADDREPLTYTOCOURSEREVIEWBYID = `${API_COURSES_PATHS.ADDREPLTYTOCOURSEREVIEWBYID}`;
const GETALLCOURSESADMIN = `${API_COURSES_PATHS.GETALLCOURSESADMIN}`;
const DELETECOURSEBYID = `${API_COURSES_PATHS.DELETECOURSEBYID}`;
const CREATECOURSE = `${API_COURSES_PATHS.CREATECOURSE}`;
const EDITCOURSEBYID = `${API_COURSES_PATHS.EDITCOURSEBYID}`;

export {
  ALLCOURSESFREE,
  GETCOURSEBYID,
  GETCOURSEBYIDFREE,
  GETCOURSECONTENTBYID,
  ADDQUESTION,
  ADDREPLYTOQUESTION,
  ADDCOURSEREVIEWBYID,
  ADDREPLTYTOCOURSEREVIEWBYID,
  GETALLCOURSESADMIN,
  DELETECOURSEBYID,
  CREATECOURSE,
  EDITCOURSEBYID,
};
