import { API_NOTIFICATION_PATHS } from "./api.routes";

////////////////////////////////// NOTIFICATION ENDPOINTS
const UPDATENOTIFCATIONSTATUS = `${API_NOTIFICATION_PATHS.UPDATENOTIFCATIONSTATUS}`;
const GETALLNOTIFCATIONS = `${API_NOTIFICATION_PATHS.GETALLNOTIFCATIONS}`;

export { UPDATENOTIFCATIONSTATUS, GETALLNOTIFCATIONS };
