import { API_USER_PATHS } from "./api.routes";

////////////////////////////////// USER ENDPOINTS
const FETCHUSER = `${API_USER_PATHS.FETCHUSER}`;
const GETUSERSLIST = `${API_USER_PATHS.GETUSERSLIST}`;
const UPDATEAVATAR = `${API_USER_PATHS.UPDATEAVATAR}`;
const UPDATEUSERINFO = `${API_USER_PATHS.UPDATEUSERINFO}`;
const UPDATEUSERPASSWORD = `${API_USER_PATHS.UPDATEUSERPASSWORD}`;
const GETADMINLIST = `${API_USER_PATHS.GETADMINLIST}`;
const GETADMIN = `${API_USER_PATHS.GETADMIN}`;
const UPDATEVIEWEDLESSON = `${API_USER_PATHS.UPDATEVIEWEDLESSON}`;
const GETALLUSERSADMIN = `${API_USER_PATHS.GETALLUSERSADMIN}`;
const UPDATEUSERROLE = `${API_USER_PATHS.UPDATEUSERROLE}`;
const DELETEUSERBYID = `${API_USER_PATHS.DELETEUSERBYID}`;
const GETUSERCOURSESSUMMARY = `${API_USER_PATHS.GETUSERCOURSESSUMMARY}`;

export {
  FETCHUSER,
  GETUSERSLIST,
  UPDATEAVATAR,
  UPDATEUSERINFO,
  UPDATEUSERPASSWORD,
  GETADMINLIST,
  GETADMIN,
  UPDATEVIEWEDLESSON,
  GETALLUSERSADMIN,
  UPDATEUSERROLE,
  DELETEUSERBYID,
  GETUSERCOURSESSUMMARY,
};
