import { API_USER_PATHS } from "./api.routes";

////////////////////////////////// USER ENDPOINTS
const FETCHUSER = `${API_USER_PATHS.FETCHUSER}`;
const GETUSERSLIST = `${API_USER_PATHS.GETUSERSLIST}`;
const UPDATEAVATAR = `${API_USER_PATHS.UPDATEAVATAR}`;
const UPDATEUSERINFO = `${API_USER_PATHS.UPDATEUSERINFO}`;
const UPDATEUSERPASSWORD = `${API_USER_PATHS.UPDATEUSERPASSWORD}`;
const GETADMINLIST = `${API_USER_PATHS.GETADMINLIST}`;
const GETADMIN = `${API_USER_PATHS.GETADMIN}`;
const UPDATEVIEWEDLESSON = `${API_USER_PATHS.UPDATEVIEWEDLESSON}`;

export {
  FETCHUSER,
  GETUSERSLIST,
  UPDATEAVATAR,
  UPDATEUSERINFO,
  UPDATEUSERPASSWORD,
  GETADMINLIST,
  GETADMIN,
  UPDATEVIEWEDLESSON,
};
